# import pandas as pd
import streamlit as st
# import matplotlib.pyplot as plt

st.header("What is Phishing?")
st.markdown("<p>Phishing is a type of online scam where an attacker sends an email, message, or creates a website that looks legitimate and tries to trick the recipient into revealing sensitive information such as usernames, passwords, or credit card numbers. Phishing attacks often use social engineering tactics to persuade the victim to click on a link or open an attachment that contains malware or directs them to a fake website that looks like a legitimate one. Once the victim enters their information, the attacker can use it for various purposes, including identity theft, financial fraud, or unauthorized access to sensitive information. Phishing attacks can be sophisticated and difficult to detect, which is why it's important to be vigilant and take precautions to protect your personal information online.</p>",unsafe_allow_html=True)

st.subheader("Factors Effecting the Detection of Phishing")

#data = pd.read_csv("processedData.csv")
length, characters, abnormal, https, cnum, ip, domain, subdomain, tld, fld, short, url_path = st.tabs(["Length","Characters", "Abnormal URLs", "HTTPS Scheme","Numbers","IP Address", "Doamin", "Sub Domain", "Top Level Domain","FLD", "Short URL", "URL path Length"])

with domain:
    st.subheader("Domain")
    st.markdown("<p>The domain name in a URL is an important component that identifies the website and its owner. In phishing attacks, attackers may use domain names that are similar to legitimate websites to trick users into visiting malicious sites and revealing sensitive information.\n\nOne common technique used in phishing attacks is to create fake login pages that mimic legitimate websites and use domain names that are similar to the legitimate website's domain name. For example, an attacker might use a domain name like \"your-bank-login.com\" instead of the legitimate domain name \"yourbank.com\". This can make the fake login page appear more legitimate and trick users into entering their login credentials or other sensitive information.\n\nAttackers may also use subdomains in domain names to create a false sense of legitimacy. For example, an attacker might create a subdomain like \"login.yourbank.com.maliciousdomain.com\" to make the URL appear to be pointing to the user's bank or another trusted organization. In reality, it is sending the user to the attacker\'s website.\n\nIn summary, the domain name in a URL is an important component that can be used by attackers in phishing attacks to make fake websites appear more legitimate. Users should always be cautious when clicking on links, verifying the legitimacy of the website, and avoiding entering sensitive information unless they are certain that the website is legitimate. They should also be aware of domain names that are similar to legitimate websites and be particularly cautious when visiting these sites.</p>",unsafe_allow_html=True)

with subdomain:
    st.subheader("Sub Domain")
    st.markdown("<p>Subdomains are a part of the domain name in a URL that comes before the main domain name and are used to organize and categorize different sections of a website. In phishing attacks, attackers may use subdomains in various ways to make fake websites appear more legitimate or to bypass security measures.One common technique used in phishing attacks is to create fake login pages that mimic legitimate websites and use subdomains that are similar to the legitimate website's subdomains. For example, an attacker might create a subdomain like \"login.yourbank.com\" to make the fake login page appear more legitimate and trick users into entering their login credentials or other sensitive information.\n\nAttackers may also use subdomains in domain names to create a false sense of legitimacy. For example, an attacker might create a subdomain like \"login.yourbank.com.maliciousdomain.com\" to make the URL appear to be pointing to the user's bank or another trusted organization. In reality, it is sending the user to the attacker's website.\n\nIn some cases, attackers may use subdomains to bypass security measures or to target specific groups of users. For example, an attacker might create a subdomain like \"hr.yourcompany.com\" to target employees of a specific company.\n\nIn summary, subdomains are a part of the domain name in a URL that attackers may use in phishing attacks to make fake websites appear more legitimate or to bypass security measures. Users should always be cautious when clicking on links, verifying the legitimacy of the website, and avoiding entering sensitive information unless they are certain that the website is legitimate. They should also be aware of subdomains that are similar to legitimate websites and be particularly cautious when visiting these sites.</p>",unsafe_allow_html=True)

with tld:
    st.subheader("Top Level Domain")
    st.markdown("<p>The TLD (Top-Level Domain) is the last part of a domain name in a URL, such as \".com\", \".org\", or \".net\". In phishing attacks, attackers may use TLDs in various ways to make fake websites appear more legitimate or to bypass security measures.\n\nOne common technique used in phishing attacks is to create fake login pages that mimic legitimate websites and use TLDs that are similar to the legitimate website's TLD. For example, an attacker might create a domain name like \"yourbank-login.net\" instead of the legitimate domain name \"yourbank.com\". This can make the fake login page appear more legitimate and trick users into entering their login credentials or other sensitive information.\n\nAttackers may also use TLDs in domain names to create a false sense of legitimacy. For example, an attacker might create a domain name like \"login.yourbank.com.maliciousdomain.net\" to make the URL appear to be pointing to the user's bank or another trusted organization. In reality, it is sending the user to the attacker's website.\n\nIn some cases, attackers may use TLDs to target specific groups of users or to bypass security measures. For example, an attacker might create a domain name with a TLD that is associated with a specific country to target users in that country.\n\nIn summary, the TLD in a URL is an important component that attackers may use in phishing attacks to make fake websites appear more legitimate or to bypass security measures. Users should always be cautious when clicking on links, verifying the legitimacy of the website, and avoiding entering sensitive information unless they are certain that the website is legitimate. They should also be aware of TLDs that are similar to legitimate websites and be particularly cautious when visiting these sites.</p>",unsafe_allow_html=True)

with fld:
    st.subheader("FLD")
    st.markdown("<p></p>",unsafe_allow_html=True)

with short:
    st.subheader("Short URLs")
    st.markdown("<p>Short URLs are abbreviated versions of longer URLs that redirect to the full URL. In phishing attacks, attackers may use short URLs to hide the actual destination of the link and trick users into visiting malicious websites.One common technique used in phishing attacks is to create short URLs that mimic legitimate URLs. For example, an attacker might create a short URL using a URL shortener service like bit.ly or goo.gl that points to a fake login page that mimics a legitimate banking website. When a user clicks on the short URL, they are redirected to the fake login page, which can then capture their login credentials or other sensitive information.Attackers may also use short URLs to bypass security measures, such as email filters or web filters that are configured to block specific domain names or URLs. By using a short URL, the attacker can hide the actual destination of the link and make it more difficult for the user or the security system to detect the phishing attempt.In summary, short URLs can be used in phishing attacks to hide the actual destination of the link and trick users into visiting malicious websites. Users should always be cautious when clicking on links, verifying the legitimacy of the website, and avoiding entering sensitive information unless they are certain that the website is legitimate. They should also be aware of short URLs and be particularly cautious when clicking on links that use them.</p>",unsafe_allow_html=True)

with url_path:
    st.subheader("URL Path length")
    st.markdown("<p>Attackers may use URLs with long or complicated paths in various ways to create a sense of urgency or legitimacy, or to obfuscate the actual destination of the link.\n\nFor example, attackers may use URLs with long or complicated paths to create fake login pages that mimic legitimate websites, and prompt users to enter their login credentials or other personal information. The length or complexity of the path can make the URL appear more legitimate, and may convince users that the website is secure and trustworthy.\n\nIn some cases, attackers may use long or complicated paths in URLs to obfuscate the actual destination of the link. For example, an attacker might use a URL with a long path that redirects the user to a malicious website or downloads malware onto the user's device.\n\nIn summary, the length of the URL path may not have a direct significance in phishing attacks, but attackers may use URLs with long or complicated paths in various ways to trick users into visiting malicious websites or revealing sensitive information. Users should always be cautious when clicking on links, verifying the legitimacy of the website, and avoiding entering sensitive information unless they are certain that the website is legitimate.</p>",unsafe_allow_html=True)

with ip:
    st.subheader("IP Address")
    st.markdown("<p>In a URL, an IP address (Internet Protocol address) is a numerical label assigned to each device connected to a computer network that uses the Internet Protocol for communication. In phishing attacks, attackers may use IP addresses in URLs to make them appear more legitimate or to bypass some security measures.\n\nOne common technique used in phishing attacks is to create fake login pages that mimic legitimate websites and use IP addresses instead of domain names in the URL. For example, an attacker might use a URL like http://192.168.1.1/your-bank-login to make the fake login page appear to be hosted on the user's own network. This can make the page appear more legitimate, as the IP address may be associated with a device on the user's network.\n\nAttackers may also use IP addresses in URLs to bypass some security measures, such as web filters or firewalls that are configured to block specific domain names or URLs. By using an IP address, the attacker can bypass these filters and make it more difficult for the user or the security system to detect the phishing attempt.\n\nIn summary, attackers may use IP addresses in URLs in phishing attacks to make fake login pages or other malicious websites appear more legitimate or to bypass security measures. Users should always be cautious when clicking on links, verifying the legitimacy of the website, and avoiding entering sensitive information unless they are certain that the website is legitimate. They should also be aware that IP addresses can be used in phishing attacks and should not rely solely on the presence of an IP address in a URL as an indication of a legitimate website.</p>",unsafe_allow_html=True)
    st.image("images/ip.png")

with cnum:
    st.subheader("Numbers")
    st.markdown("<p>Attackers may use URLs with numbers to create fake login pages that mimic legitimate websites and prompt users to enter their login credentials or other sensitive information. The URLs may include numbers to make them appear more legitimate, such as by including a specific date or time, or a transaction or order number.\n\nAttackers may also use URLs with numbers in phishing emails, such as by including a phone number to call or a reference number to provide when contacting customer support. These numbers may be used to trick users into revealing sensitive information, such as account numbers or passwords.\n\nIn summary, the count of digits in a URL may not have a direct significance in phishing attacks, but attackers may use URLs with numbers to create a sense of urgency or legitimacy and trick users into disclosing sensitive information. Users should always be cautious when clicking on links, verifying the legitimacy of the website, and avoiding entering sensitive information unless they are certain that the website is legitimate.</p>",unsafe_allow_html=True)

with https:
    st.subheader("HTTPS Scheme")
    st.markdown("<p>The \"https\" scheme in a URL refers to the use of an encrypted connection between the user's browser and the website server, which helps to protect the privacy and security of the user's information. In phishing attacks, attackers may use fake \"https\" URLs to create a false sense of security and trick users into entering sensitive information.\n\nOne common technique used in phishing attacks is to create fake login pages that mimic legitimate websites, such as banks or social media sites, and use \"https\" URLs to make the pages appear secure. These fake login pages may include fields for users to enter their login credentials or other personal information, which the attacker can then use for nefarious purposes.\n\nIn some cases, attackers may also use other techniques to make their fake \"https\" URLs appear more legitimate, such as including a padlock icon in the browser's address bar or using a URL that includes a trusted domain name. However, these techniques are not foolproof, and users should always be cautious when entering sensitive information on any website.\n\nIn summary, the \"https\" scheme in a URL is intended to provide a secure and encrypted connection between the user's browser and the website server. However, attackers may use fake \"https\" URLs as part of phishing attacks to trick users into entering sensitive information on fake login pages or other malicious websites. Users should always verify the legitimacy of any website before entering sensitive information, even if the website uses an \"https\" URL.</p>",unsafe_allow_html=True)


with abnormal:
    st.subheader("Abnormal URLs")
    st.markdown("Abnormal URLs are URLs that differ from the usual patterns that users are accustomed to seeing. They can be used in phishing attacks to trick users into visiting malicious websites or to create fake login pages that capture users' sensitive information.\n\nOne common technique used in phishing attacks is to create abnormal URLs that are similar to legitimate URLs but with slight variations that may go unnoticed by the user. For example, an attacker might create a URL like http://www.your-bank.com (with a hyphen instead of a dot between \"your\" and \"bank\"). This URL may look similar enough to the legitimate URL (http://www.yourbank.com) that a user might not notice the difference and enter their login information on the fake site.\n\nAnother way that abnormal URLs can be used in phishing attacks is by creating URLs that include encoded special characters in the domain name or subdomains. For example, an attacker might create a URL like http://you%72bank.com. In this URL, the \"%\" character is used to encode the \"r\" character in the domain name. This URL may look like it is pointing to a legitimate website, but in reality, it is pointing to a malicious site.\n\nIn summary, abnormal URLs are often used in phishing attacks to create URLs that appear to be legitimate but are actually designed to trick users into giving up sensitive information. Users should always be cautious when clicking on links and should verify the legitimacy of the website before entering any sensitive information. They should also be aware of unusual or abnormal URLs and be particularly cautious when visiting these sites.",unsafe_allow_html=True)
    st.image("images/abnormal.png")

with characters:
    st.subheader("Characters")
    st.markdown("<p>Special characters in URLs can be used by attackers to create URLs that appear to be legitimate but are actually designed to trick users into giving up sensitive information. Attackers may use special characters to encode malicious code, obfuscate the URL, or create fake subdomains that appear to be part of a legitimate domain. For example, attackers may use the \"-\" character to create a fake subdomain that looks like it is part of a legitimate domain or use the \"@\" character to create a fake email address. It is important for users to be cautious when clicking on links and to verify the legitimacy of the website before entering any sensitive information.</p>",unsafe_allow_html=True)
    st.image("images/char.png")
    char1, char2, char3, char4, char5, char6, char7, char8, char9, char10, char11, char12, char13 =st.tabs(["@","?","\-","=",".","\#","%","\+","$","!","\*",",","//"])

with char13:
    st.subheader("Character '//'")
    st.markdown("<p>The \"//\" character sequence is commonly used in URLs to indicate the start of the domain name or the protocol being used, such as \"http://\" or \"https://\". In phishing attacks, attackers may use the \"//\" sequence as part of a larger strategy to create URLs that appear to be legitimate but are actually designed to trick users into giving up sensitive information.\n\nOne common technique used in phishing attacks is to create URLs that are similar to legitimate URLs but with slight variations that may go unnoticed by the user. For example, an attacker might create a URL like http://www.your-bank.com (with a hyphen instead of a dot between \"your\" and \"bank\"). This URL may look similar enough to the legitimate URL (http://www.yourbank.com) that a user might not notice the difference and enter their login information on the fake site.\n\nSimilarly, attackers may use the \"//\" sequence in URLs to create subdomains that appear to be part of a legitimate domain. For example, an attacker might create a URL like http://yourbank-login.maliciousdomain.com. This can make the URL appear to be pointing to the user's bank or another trusted organization, but in reality, it is sending the user to the attacker's website.\n\nIn summary, the \"//\" character sequence itself is not significant in phishing attacks, but attackers may use it as part of a larger strategy to create URLs that appear to be legitimate but are actually designed to trick users into giving up sensitive information. Users should always be cautious when clicking on links and should verify the legitimacy of the website before entering any sensitive information.</p>",unsafe_allow_html=True)
    st.image("images/char2.png")

with char12:
    st.subheader("Character ','")
    st.markdown("<p>The \",\" character is not commonly used in URLs and does not have any inherent significance in phishing attacks. However, attackers may use the \",\" character as part of a larger strategy to create URLs that appear to be legitimate but are actually designed to trick users into giving up sensitive information.\n\nOne common technique used in phishing attacks is to create URLs that are similar to legitimate URLs but with slight variations that may go unnoticed by the user. For example, an attacker might create a URL like http://www.your-bank.com (with a hyphen instead of a dot between \"your\" and \"bank\"). This URL may look similar enough to the legitimate URL (http://www.yourbank.com) that a user might not notice the difference and enter their login information on the fake site.\n\nSimilarly, attackers may use the \",\" character in URLs to create subdomains that appear to be part of a legitimate domain. For example, an attacker might create a URL like http://yourbank-login.maliciousdomain.com. This can make the URL appear to be pointing to the user's bank or another trusted organization, but in reality, it is sending the user to the attacker's website.\n\nIn summary, the \",\" character itself is not significant in phishing attacks, but attackers may use it as part of a larger strategy to create URLs that appear to be legitimate but are actually designed to trick users into giving up sensitive information. Users should always be cautious when clicking on links and should verify the legitimacy of the website before entering any sensitive information.</p>",unsafe_allow_html=True)

with char11:
    st.subheader("Character '*'")
    st.markdown("<p>The \"*\" character is not commonly used in URLs and does not have any inherent significance in phishing attacks. However, attackers may use the \"*\" character as part of a larger strategy to create URLs that appear to be legitimate but are actually designed to trick users into giving up sensitive information.\n\nOne common technique used in phishing attacks is to create URLs that are similar to legitimate URLs but with slight variations that may go unnoticed by the user. For example, an attacker might create a URL like http://www.your-bank.com (with a hyphen instead of a dot between \"your\" and \"bank\"). This URL may look similar enough to the legitimate URL (http://www.yourbank.com) that a user might not notice the difference and enter their login information on the fake site.\n\nSimilarly, attackers may use the \"*\" character in URLs to create subdomains that appear to be part of a legitimate domain. For example, an attacker might create a URL like http://yourbank-login.maliciousdomain.com. This can make the URL appear to be pointing to the user's bank or another trusted organization, but in reality, it is sending the user to the attacker's website.\n\nIn summary, the \"*\" character itself is not significant in phishing attacks, but attackers may use it as part of a larger strategy to create URLs that appear to be legitimate but are actually designed to trick users into giving up sensitive information. Users should always be cautious when clicking on links and should verify the legitimacy of the website before entering any sensitive information.</p>",unsafe_allow_html=True)

with char10:
    st.subheader("Character '!'")
    st.markdown("<p>The \"!\" character is not commonly used in URLs and does not have any inherent significance in phishing attacks. However, attackers may use the \"!\" character as part of a larger strategy to create URLs that appear to be legitimate but are actually designed to trick users into giving up sensitive information.\n\nOne common technique used in phishing attacks is to create URLs that are similar to legitimate URLs but with slight variations that may go unnoticed by the user. For example, an attacker might create a URL like http://www.your-bank.com (with a hyphen instead of a dot between \"your\" and \"bank\"). This URL may look similar enough to the legitimate URL (http://www.yourbank.com) that a user might not notice the difference and enter their login information on the fake site.\n\nSimilarly, attackers may use the \"!\" character in URLs to create subdomains that appear to be part of a legitimate domain. For example, an attacker might create a URL like http://yourbank-login.maliciousdomain.com. This can make the URL appear to be pointing to the user's bank or another trusted organization, but in reality, it is sending the user to the attacker's website.\n\nIn summary, the \"!\" character itself is not significant in phishing attacks, but attackers may use it as part of a larger strategy to create URLs that appear to be legitimate but are actually designed to trick users into giving up sensitive information. Users should always be cautious when clicking on links and should verify the legitimacy of the website before entering any sensitive information.</p>",unsafe_allow_html=True)

with char9:
    st.subheader("Character '$'")
    st.markdown("<p>The \"$\" character is not commonly used in URLs and does not have any inherent significance in phishing attacks. However, attackers may use the \"$\" character as part of a larger strategy to create URLs that appear to be legitimate but are actually designed to trick users into giving up sensitive information.\n\nOne common technique used in phishing attacks is to create URLs that are similar to legitimate URLs but with slight variations that may go unnoticed by the user. For example, an attacker might create a URL like http://www.your-bank.com (with a hyphen instead of a dot between \"your\" and \"bank\"). This URL may look similar enough to the legitimate URL (http://www.yourbank.com) that a user might not notice the difference and enter their login information on the fake site.\n\nSimilarly, attackers may use the \"$\" character in URLs to create subdomains that appear to be part of a legitimate domain. For example, an attacker might create a URL like http://yourbank-login.maliciousdomain.com. This can make the URL appear to be pointing to the user's bank or another trusted organization, but in reality, it is sending the user to the attacker's website.\n\nIn summary, the \"$\" character itself is not significant in phishing attacks, but attackers may use it as part of a larger strategy to create URLs that appear to be legitimate but are actually designed to trick users into giving up sensitive information. Users should always be cautious when clicking on links and should verify the legitimacy of the website before entering any sensitive information.</p>",unsafe_allow_html=True)
    st.image("images/char$.png")

with char8:
    st.subheader("Character '+'")
    st.markdown("<p>The \"+\" character is used in URLs to encode spaces or to separate words in a query string parameter. In phishing attacks, attackers may use the \"+\" character to create URLs that appear to be legitimate, but are actually designed to trick users into providing sensitive information.\n\nOne common technique used in phishing attacks is to create URLs that include a fake login page. When a user clicks on the link, they are taken to a page that looks like a legitimate login page for a well-known service, such as a bank or social media site. The URL for the fake login page may include encoded spaces in the query string that are used to capture the user's login information. For example, an attacker might create a URL like http://yourbank.com/login.php?username=john+doe&password=123+456. In this URL, the \"+\" character is used to represent a space character in the username and to separate the words in the password. When the user enters their login information on the fake login page, the attacker captures their username and password.\n\nAnother way that the \"+\" character can be used in phishing attacks is by creating URLs that include encoded special characters in the domain name or subdomains. For example, an attacker might create a URL like http://you+rba+nk.com. In this URL, the \"+\" character is used to represent spaces in the domain name. This URL may look like it is pointing to a legitimate website, but in reality, it is pointing to a malicious site.\n\nIn summary, the \"+\" character can be used in phishing attacks to create URLs that appear to be legitimate, but are actually designed to capture sensitive information. Users should always be cautious when clicking on links and should verify the legitimacy of the website before entering any sensitive information.</p>",unsafe_allow_html=True)

with length:
    st.subheader("Length of URL")
    st.markdown('<p>The length of a URL can be a factor in phishing attacks in a few different ways.\n\nFirstly, phishing websites often use long, complex URLs to obscure their true nature. By making the URL difficult to read and understand, attackers hope to trick users into clicking on links that they might otherwise avoid.\n\nConversely, legitimate websites often have shorter, simpler URLs that are easier to read and remember. This means that users may be more likely to trust a website with a short URL and less likely to trust a website with a long, complicated URL.\n\nAdditionally, attackers may use a technique called URL spoofing to make a fake website look like a legitimate one by using a long URL that includes the name of the legitimate website. This can make it more difficult for users to recognize that they are on a fake website and may lead them to enter sensitive information, such as passwords or credit card numbers.\n\nIn summary, the length of a URL can be a factor in phishing attacks because attackers may use long, complex URLs to obscure their true nature, or to make fake websites look more like legitimate ones. Conversely, shorter, simpler URLs may be more associated with legitimate websites and can help users identify and avoid phishing attempts.</p>',unsafe_allow_html=True)
    st.image("images/length.png")

with char1:
        
    st.subheader("Character '@'")

    st.write("<p>The \"@\" character is not commonly used in URLs and is typically reserved for email addresses. However, in some cases, attackers may use the \"@\" character in a URL as part of a phishing attack.\n\nOne technique used in phishing attacks is to create URLs that contain a username and password, separated by the \"@\" character. This can make the URL look like it is pointing to a legitimate login page, but in reality, it is sending the username and password to the attacker's server. For example, an attacker might create a URL like http://username:password@maliciousdomain.com. If a user clicks on this link and enters their login information, the attacker can steal their credentials.\n\nAnother way that the \"@\" character can be used in phishing attacks is by creating URLs that include the name of a legitimate company or organization, followed by \"@maliciousdomain.com.\" For example, an attacker might create a URL like http://yourbank.com@maliciousdomain.com. This can make the URL appear to be pointing to the user's bank or another trusted organization, but in reality, it is sending the user to the attacker's website.\n\nIn summary, while the \"@\" character is not commonly used in URLs, it can be used in phishing attacks to create URLs that look like they are pointing to legitimate login pages or trusted organizations, but are actually sending information to the attacker's server. Users should always be cautious when clicking on links and should verify the legitimacy of the website before entering any sensitive information.</p>",unsafe_allow_html=True)

with char2:
    st.subheader("Character '?'")

    st.markdown("<p>The \"?\" character is used in URLs to separate the URL path from the query string, which contains parameters that are used to pass data to a web application. In phishing attacks, attackers may use the \"?\" character to create URLs that appear to be legitimate, but are actually designed to trick users into providing sensitive information.\n\n   One common technique used in phishing attacks is to create URLs that include a fake login page. When a user clicks on the link, they are taken to a page that looks like a legitimate login page for a well-known service, such as a bank or social media site. The URL for the fake login page may include parameters in the query string that are used to capture the user's login information. For example, an attacker might create a URL like http://yourbank.com/login.php?username=johndoe&password=123456. When the user enters their login information on the fake login page, the attacker captures their username and password.\n\nAnother way that the \"?\" character can be used in phishing attacks is by creating URLs that include parameters that are designed to exploit vulnerabilities in web applications. For example, an attacker might create a URL like http://yourbank.com/transfer.php?to=attacker&amount=1000000. If the bank's web application does not properly validate user input, the attacker may be able to use this URL to transfer funds from the user's account to their own.\n\n   In summary, the \"?\" character can be used in phishing attacks to create URLs that appear to be legitimate, but are actually designed to capture sensitive information or exploit vulnerabilities in web applications. Users should always be cautious when clicking on links and should verify the legitimacy of the website before entering any sensitive information.</p>",unsafe_allow_html=True)

with char3:
    st.subheader("Character '-'")

    st.markdown("<p>The \"-\" character is commonly used in URLs to separate words or phrases, and is generally not significant in phishing attacks in and of itself. However, attackers may use the \"-\" character as part of a larger strategy to create URLs that appear to be legitimate but are actually designed to trick users into giving up sensitive information.\n\nOne technique used in phishing attacks is to create URLs that are similar to legitimate URLs but with slight variations that may go unnoticed by the user. For example, an attacker might create a URL like http://www.your-bank.com (with a hyphen instead of a dot between \"your\" and \"bank\"). This URL may look similar enough to the legitimate URL (http://www.yourbank.com) that a user might not notice the difference and enter their login information on the fake site.\n\nSimilarly, attackers may use the \"-\" character in URLs to create subdomains that appear to be part of a legitimate domain. For example, an attacker might create a URL like http://yourbank-login.maliciousdomain.com. This URL may look like it is a legitimate subdomain of yourbank.com, but in reality, it is pointing to a malicious domain.\n\nIn summary, the \"-\" character is not significant in and of itself in phishing attacks, but attackers may use it as part of a larger strategy to create URLs that appear to be legitimate but are actually designed to trick users into giving up sensitive information. Users should always be cautious when clicking on links and should verify the legitimacy of the website before entering any sensitive information.</p>",unsafe_allow_html=True)

with char4:
    st.subheader("Character '='")
    st.markdown("<p>The \"=\" character is used in URLs to separate parameter names from their values in the query string. In phishing attacks, attackers may use the \"=\" character to create URLs that appear to be legitimate, but are actually designed to trick users into providing sensitive information.\n\nOne common technique used in phishing attacks is to create URLs that include a fake login page. When a user clicks on the link, they are taken to a page that looks like a legitimate login page for a well-known service, such as a bank or social media site. The URL for the fake login page may include parameters in the query string that are used to capture the user's login information. For example, an attacker might create a URL like http://yourbank.com/login.php?username=johndoe&password=123456. In this URL, the \"=\" character is used to separate the parameter names (username and password) from their values (johndoe and 123456). When the user enters their login information on the fake login page, the attacker captures their username and password.\n\nAnother way that the \"=\" character can be used in phishing attacks is by creating URLs that include parameters that are designed to exploit vulnerabilities in web applications. For example, an attacker might create a URL like http://yourbank.com/transfer.php?to=attacker&amount=1000000. In this URL, the \"=\" character is used to separate the parameter names (to and amount) from their values (attacker and 1000000). If the bank's web application does not properly validate user input, the attacker may be able to use this URL to transfer funds from the user's account to their own.\n\nIn summary, the \"=\" character can be used in phishing attacks to create URLs that appear to be legitimate, but are actually designed to capture sensitive information or exploit vulnerabilities in web applications. Users should always be cautious when clicking on links and should verify the legitimacy of the website before entering any sensitive information.</p>",unsafe_allow_html=True)

with char5:
    st.subheader("Character '.'")
    st.markdown("<p>The \".\" character is commonly used in URLs to separate domain names and subdomains, and is generally not significant in phishing attacks in and of itself. However, attackers may use the \".\" character as part of a larger strategy to create URLs that appear to be legitimate but are actually designed to trick users into giving up sensitive information.\n\nOne common technique used in phishing attacks is to create URLs that are similar to legitimate URLs but with slight variations that may go unnoticed by the user. For example, an attacker might create a URL like http://www.your-bank.com (with a hyphen instead of a dot between \"your\" and \"bank\"). This URL may look similar enough to the legitimate URL (http://www.yourbank.com) that a user might not notice the difference and enter their login information on the fake site.\n\nAnother way that attackers may use the \".\" character in URLs is by creating URLs that include subdomains that appear to be part of a legitimate domain. For example, an attacker might create a URL like http://login.yourbank.com.maliciousdomain.com. This URL may look like it is a legitimate subdomain of yourbank.com, but in reality, it is pointing to a malicious domain.\n\nIn summary, the \".\" character is not significant in and of itself in phishing attacks, but attackers may use it as part of a larger strategy to create URLs that appear to be legitimate but are actually designed to trick users into giving up sensitive information. Users should always be cautious when clicking on links and should verify the legitimacy of the website before entering any sensitive information.</p>",unsafe_allow_html=True)

with char6:
    st.subheader("Character '#'")
    st.markdown("<p>The \"#\" character is used in URLs to separate the fragment identifier from the rest of the URL. The fragment identifier is a way to identify a specific section of a webpage and is typically used for linking to specific sections of a webpage or for bookmarking.\n\nIn phishing attacks, the \"#\" character is not typically used in isolation as a way to deceive users into divulging sensitive information. However, attackers may use the \"#\" character as part of a larger strategy to create URLs that appear to be legitimate but are actually designed to trick users into giving up sensitive information.\n\nFor example, an attacker may create a URL that looks like it is linking to a legitimate website, but in reality, the URL contains parameters in the query string that are used to capture the user's login information. The \"#\" character may be used in the URL to hide the query string from the user's view. When the user clicks on the link, they are taken to a page that looks like a legitimate login page, but the attacker captures their username and password.\n\nIn summary, the \"#\" character itself is not significant in phishing attacks, but attackers may use it as part of a larger strategy to create URLs that appear to be legitimate but are actually designed to trick users into giving up sensitive information. Users should always be cautious when clicking on links and should verify the legitimacy of the website before entering any sensitive information.</p>",unsafe_allow_html=True)

with char7:
    st.subheader("Character '%'")
    st.markdown("<p>The \"%\" character is used in URLs to encode special characters that are not allowed in a URL, such as spaces, question marks, and ampersands. In phishing attacks, attackers may use the \"%\" character to create URLs that appear to be legitimate, but are actually designed to trick users into providing sensitive information.\n\nOne common technique used in phishing attacks is to create URLs that include a fake login page. When a user clicks on the link, they are taken to a page that looks like a legitimate login page for a well-known service, such as a bank or social media site. The URL for the fake login page may include encoded special characters in the query string that are used to capture the user's login information. For example, an attacker might create a URL like http://yourbank.com/login.php?username=john%20doe&password=123%25456. In this URL, the \"%\" character is used to encode a space character in the username and the \"%\" and \"4\" characters in the password. When the user enters their login information on the fake login page, the attacker captures their username and password.\n\nAnother way that the \"%\" character can be used in phishing attacks is by creating URLs that include encoded special characters in the domain name or subdomains. For example, an attacker might create a URL like http://you%72bank.com. In this URL, the \"%\" character is used to encode the \"r\" character in the domain name. This URL may look like it is pointing to a legitimate website, but in reality, it is pointing to a malicious site.\n\nIn summary, the \"%\" character can be used in phishing attacks to create URLs that appear to be legitimate, but are actually designed to capture sensitive information. Users should always be cautious when clicking on links and should verify the legitimacy of the website before entering any sensitive information.</p>",unsafe_allow_html=True)